### ISSUE TITLE
Openstack environment variable OS_USERNAME set wrong as OS_USER_NAME on collector.py

### ISSUE THREAD

**Issue by amsaha** [CiscoZeus/don#13]

**Comment by amsaha** [comment]
Traceback (most recent call last):
File "vm_details_collector.py", line 244, in
print main()
File "vm_details_collector.py", line 241, in main
return vms_details()
File "vm_details_collector.py", line 226, in vms_details
a1 = execute_cmd(['nova', 'list'], sudo=False, shell=False, env=env).split('\n');
File "vm_details_collector.py", line 168, in execute_cmd
universal_newlines=True).replace('\t', ' ')
File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['nova', 'list']' returned non-zero exit status 1

**Comment by amsaha** [comment]
Fixed via pull request https://github.com/CiscoZeus/don/pull/21. This issue is no longer relevant anyway.
